/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RezervacijaRouteImport } from './routes/rezervacija'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SesijaTokenRouteImport } from './routes/sesija.$token'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiPlanSuggestRouteImport } from './routes/api/plan-suggest'
import { Route as ApiMentorChatRouteImport } from './routes/api/mentor-chat'
import { Route as ApiKnowledgeIngestRouteImport } from './routes/api/knowledge-ingest'
import { Route as ApiGoalBreakdownRouteImport } from './routes/api/goal-breakdown'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVisionRouteImport } from './routes/_authenticated/vision'
import { Route as AuthenticatedSessionRouteImport } from './routes/_authenticated/session'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrioritiesRouteImport } from './routes/_authenticated/priorities'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAskIndexRouteImport } from './routes/_authenticated/ask.index'
import { Route as SesijaTokenPabaigaRouteImport } from './routes/sesija.$token.pabaiga'
import { Route as AuthenticatedAskThreadIdRouteImport } from './routes/_authenticated/ask.$threadId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicClarityMessageRouteImport } from './routes/api/public/clarity/message'
import { Route as ApiPublicClarityInterestRouteImport } from './routes/api/public/clarity/interest'
import { Route as ApiPublicClarityFinishRouteImport } from './routes/api/public/clarity/finish'
import { Route as ApiPublicClarityBookRouteImport } from './routes/api/public/clarity/book'

const RezervacijaRoute = RezervacijaRouteImport.update({
  id: '/rezervacija',
  path: '/rezervacija',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SesijaTokenRoute = SesijaTokenRouteImport.update({
  id: '/sesija/$token',
  path: '/sesija/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanSuggestRoute = ApiPlanSuggestRouteImport.update({
  id: '/api/plan-suggest',
  path: '/api/plan-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorChatRoute = ApiMentorChatRouteImport.update({
  id: '/api/mentor-chat',
  path: '/api/mentor-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeIngestRoute = ApiKnowledgeIngestRouteImport.update({
  id: '/api/knowledge-ingest',
  path: '/api/knowledge-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoalBreakdownRoute = ApiGoalBreakdownRouteImport.update({
  id: '/api/goal-breakdown',
  path: '/api/goal-breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisionRoute = AuthenticatedVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionRoute = AuthenticatedSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrioritiesRoute = AuthenticatedPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAskIndexRoute = AuthenticatedAskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAskRoute,
} as any)
const SesijaTokenPabaigaRoute = SesijaTokenPabaigaRouteImport.update({
  id: '/pabaiga',
  path: '/pabaiga',
  getParentRoute: () => SesijaTokenRoute,
} as any)
const AuthenticatedAskThreadIdRoute =
  AuthenticatedAskThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAskRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClarityMessageRoute = ApiPublicClarityMessageRouteImport.update({
  id: '/api/public/clarity/message',
  path: '/api/public/clarity/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClarityInterestRoute =
  ApiPublicClarityInterestRouteImport.update({
    id: '/api/public/clarity/interest',
    path: '/api/public/clarity/interest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClarityFinishRoute = ApiPublicClarityFinishRouteImport.update({
  id: '/api/public/clarity/finish',
  path: '/api/public/clarity/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClarityBookRoute = ApiPublicClarityBookRouteImport.update({
  id: '/api/public/clarity/book',
  path: '/api/public/clarity/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/rezervacija': typeof RezervacijaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ask': typeof AuthenticatedAskRouteWithChildren
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/session': typeof AuthenticatedSessionRoute
  '/vision': typeof AuthenticatedVisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/goal-breakdown': typeof ApiGoalBreakdownRoute
  '/api/knowledge-ingest': typeof ApiKnowledgeIngestRoute
  '/api/mentor-chat': typeof ApiMentorChatRoute
  '/api/plan-suggest': typeof ApiPlanSuggestRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/sesija/$token': typeof SesijaTokenRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/ask/$threadId': typeof AuthenticatedAskThreadIdRoute
  '/sesija/$token/pabaiga': typeof SesijaTokenPabaigaRoute
  '/ask/': typeof AuthenticatedAskIndexRoute
  '/api/public/clarity/book': typeof ApiPublicClarityBookRoute
  '/api/public/clarity/finish': typeof ApiPublicClarityFinishRoute
  '/api/public/clarity/interest': typeof ApiPublicClarityInterestRoute
  '/api/public/clarity/message': typeof ApiPublicClarityMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/rezervacija': typeof RezervacijaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/session': typeof AuthenticatedSessionRoute
  '/vision': typeof AuthenticatedVisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/goal-breakdown': typeof ApiGoalBreakdownRoute
  '/api/knowledge-ingest': typeof ApiKnowledgeIngestRoute
  '/api/mentor-chat': typeof ApiMentorChatRoute
  '/api/plan-suggest': typeof ApiPlanSuggestRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/sesija/$token': typeof SesijaTokenRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/ask/$threadId': typeof AuthenticatedAskThreadIdRoute
  '/sesija/$token/pabaiga': typeof SesijaTokenPabaigaRoute
  '/ask': typeof AuthenticatedAskIndexRoute
  '/api/public/clarity/book': typeof ApiPublicClarityBookRoute
  '/api/public/clarity/finish': typeof ApiPublicClarityFinishRoute
  '/api/public/clarity/interest': typeof ApiPublicClarityInterestRoute
  '/api/public/clarity/message': typeof ApiPublicClarityMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/rezervacija': typeof RezervacijaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/ask': typeof AuthenticatedAskRouteWithChildren
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/priorities': typeof AuthenticatedPrioritiesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/session': typeof AuthenticatedSessionRoute
  '/_authenticated/vision': typeof AuthenticatedVisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/goal-breakdown': typeof ApiGoalBreakdownRoute
  '/api/knowledge-ingest': typeof ApiKnowledgeIngestRoute
  '/api/mentor-chat': typeof ApiMentorChatRoute
  '/api/plan-suggest': typeof ApiPlanSuggestRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/sesija/$token': typeof SesijaTokenRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/ask/$threadId': typeof AuthenticatedAskThreadIdRoute
  '/sesija/$token/pabaiga': typeof SesijaTokenPabaigaRoute
  '/_authenticated/ask/': typeof AuthenticatedAskIndexRoute
  '/api/public/clarity/book': typeof ApiPublicClarityBookRoute
  '/api/public/clarity/finish': typeof ApiPublicClarityFinishRoute
  '/api/public/clarity/interest': typeof ApiPublicClarityInterestRoute
  '/api/public/clarity/message': typeof ApiPublicClarityMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/rezervacija'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ask'
    | '/goals'
    | '/insights'
    | '/journal'
    | '/knowledge'
    | '/priorities'
    | '/profile'
    | '/progress'
    | '/resources'
    | '/session'
    | '/vision'
    | '/api/chat'
    | '/api/goal-breakdown'
    | '/api/knowledge-ingest'
    | '/api/mentor-chat'
    | '/api/plan-suggest'
    | '/api/transcribe'
    | '/sesija/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/ask/$threadId'
    | '/sesija/$token/pabaiga'
    | '/ask/'
    | '/api/public/clarity/book'
    | '/api/public/clarity/finish'
    | '/api/public/clarity/interest'
    | '/api/public/clarity/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/rezervacija'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/goals'
    | '/insights'
    | '/journal'
    | '/knowledge'
    | '/priorities'
    | '/profile'
    | '/progress'
    | '/resources'
    | '/session'
    | '/vision'
    | '/api/chat'
    | '/api/goal-breakdown'
    | '/api/knowledge-ingest'
    | '/api/mentor-chat'
    | '/api/plan-suggest'
    | '/api/transcribe'
    | '/sesija/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/ask/$threadId'
    | '/sesija/$token/pabaiga'
    | '/ask'
    | '/api/public/clarity/book'
    | '/api/public/clarity/finish'
    | '/api/public/clarity/interest'
    | '/api/public/clarity/message'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/rezervacija'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/ask'
    | '/_authenticated/goals'
    | '/_authenticated/insights'
    | '/_authenticated/journal'
    | '/_authenticated/knowledge'
    | '/_authenticated/priorities'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/resources'
    | '/_authenticated/session'
    | '/_authenticated/vision'
    | '/api/chat'
    | '/api/goal-breakdown'
    | '/api/knowledge-ingest'
    | '/api/mentor-chat'
    | '/api/plan-suggest'
    | '/api/transcribe'
    | '/sesija/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/ask/$threadId'
    | '/sesija/$token/pabaiga'
    | '/_authenticated/ask/'
    | '/api/public/clarity/book'
    | '/api/public/clarity/finish'
    | '/api/public/clarity/interest'
    | '/api/public/clarity/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  RezervacijaRoute: typeof RezervacijaRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGoalBreakdownRoute: typeof ApiGoalBreakdownRoute
  ApiKnowledgeIngestRoute: typeof ApiKnowledgeIngestRoute
  ApiMentorChatRoute: typeof ApiMentorChatRoute
  ApiPlanSuggestRoute: typeof ApiPlanSuggestRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  SesijaTokenRoute: typeof SesijaTokenRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicClarityBookRoute: typeof ApiPublicClarityBookRoute
  ApiPublicClarityFinishRoute: typeof ApiPublicClarityFinishRoute
  ApiPublicClarityInterestRoute: typeof ApiPublicClarityInterestRoute
  ApiPublicClarityMessageRoute: typeof ApiPublicClarityMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rezervacija': {
      id: '/rezervacija'
      path: '/rezervacija'
      fullPath: '/rezervacija'
      preLoaderRoute: typeof RezervacijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesija/$token': {
      id: '/sesija/$token'
      path: '/sesija/$token'
      fullPath: '/sesija/$token'
      preLoaderRoute: typeof SesijaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan-suggest': {
      id: '/api/plan-suggest'
      path: '/api/plan-suggest'
      fullPath: '/api/plan-suggest'
      preLoaderRoute: typeof ApiPlanSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor-chat': {
      id: '/api/mentor-chat'
      path: '/api/mentor-chat'
      fullPath: '/api/mentor-chat'
      preLoaderRoute: typeof ApiMentorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge-ingest': {
      id: '/api/knowledge-ingest'
      path: '/api/knowledge-ingest'
      fullPath: '/api/knowledge-ingest'
      preLoaderRoute: typeof ApiKnowledgeIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/goal-breakdown': {
      id: '/api/goal-breakdown'
      path: '/api/goal-breakdown'
      fullPath: '/api/goal-breakdown'
      preLoaderRoute: typeof ApiGoalBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vision': {
      id: '/_authenticated/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof AuthenticatedVisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session': {
      id: '/_authenticated/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AuthenticatedSessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priorities': {
      id: '/_authenticated/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof AuthenticatedPrioritiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ask/': {
      id: '/_authenticated/ask/'
      path: '/'
      fullPath: '/ask/'
      preLoaderRoute: typeof AuthenticatedAskIndexRouteImport
      parentRoute: typeof AuthenticatedAskRoute
    }
    '/sesija/$token/pabaiga': {
      id: '/sesija/$token/pabaiga'
      path: '/pabaiga'
      fullPath: '/sesija/$token/pabaiga'
      preLoaderRoute: typeof SesijaTokenPabaigaRouteImport
      parentRoute: typeof SesijaTokenRoute
    }
    '/_authenticated/ask/$threadId': {
      id: '/_authenticated/ask/$threadId'
      path: '/$threadId'
      fullPath: '/ask/$threadId'
      preLoaderRoute: typeof AuthenticatedAskThreadIdRouteImport
      parentRoute: typeof AuthenticatedAskRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/message': {
      id: '/api/public/clarity/message'
      path: '/api/public/clarity/message'
      fullPath: '/api/public/clarity/message'
      preLoaderRoute: typeof ApiPublicClarityMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/interest': {
      id: '/api/public/clarity/interest'
      path: '/api/public/clarity/interest'
      fullPath: '/api/public/clarity/interest'
      preLoaderRoute: typeof ApiPublicClarityInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/finish': {
      id: '/api/public/clarity/finish'
      path: '/api/public/clarity/finish'
      fullPath: '/api/public/clarity/finish'
      preLoaderRoute: typeof ApiPublicClarityFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/book': {
      id: '/api/public/clarity/book'
      path: '/api/public/clarity/book'
      fullPath: '/api/public/clarity/book'
      preLoaderRoute: typeof ApiPublicClarityBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAskRouteChildren {
  AuthenticatedAskThreadIdRoute: typeof AuthenticatedAskThreadIdRoute
  AuthenticatedAskIndexRoute: typeof AuthenticatedAskIndexRoute
}

const AuthenticatedAskRouteChildren: AuthenticatedAskRouteChildren = {
  AuthenticatedAskThreadIdRoute: AuthenticatedAskThreadIdRoute,
  AuthenticatedAskIndexRoute: AuthenticatedAskIndexRoute,
}

const AuthenticatedAskRouteWithChildren =
  AuthenticatedAskRoute._addFileChildren(AuthenticatedAskRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAskRoute: typeof AuthenticatedAskRouteWithChildren
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedPrioritiesRoute: typeof AuthenticatedPrioritiesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSessionRoute: typeof AuthenticatedSessionRoute
  AuthenticatedVisionRoute: typeof AuthenticatedVisionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAskRoute: AuthenticatedAskRouteWithChildren,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedPrioritiesRoute: AuthenticatedPrioritiesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSessionRoute: AuthenticatedSessionRoute,
  AuthenticatedVisionRoute: AuthenticatedVisionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SesijaTokenRouteChildren {
  SesijaTokenPabaigaRoute: typeof SesijaTokenPabaigaRoute
}

const SesijaTokenRouteChildren: SesijaTokenRouteChildren = {
  SesijaTokenPabaigaRoute: SesijaTokenPabaigaRoute,
}

const SesijaTokenRouteWithChildren = SesijaTokenRoute._addFileChildren(
  SesijaTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  RezervacijaRoute: RezervacijaRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGoalBreakdownRoute: ApiGoalBreakdownRoute,
  ApiKnowledgeIngestRoute: ApiKnowledgeIngestRoute,
  ApiMentorChatRoute: ApiMentorChatRoute,
  ApiPlanSuggestRoute: ApiPlanSuggestRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  SesijaTokenRoute: SesijaTokenRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicClarityBookRoute: ApiPublicClarityBookRoute,
  ApiPublicClarityFinishRoute: ApiPublicClarityFinishRoute,
  ApiPublicClarityInterestRoute: ApiPublicClarityInterestRoute,
  ApiPublicClarityMessageRoute: ApiPublicClarityMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
