/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RezervacijaRouteImport } from './routes/rezervacija'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SesijaTokenRouteImport } from './routes/sesija.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiVisionAlignmentRouteImport } from './routes/api/vision-alignment'
import { Route as ApiValueSimilaritiesRouteImport } from './routes/api/value-similarities'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiPlanSuggestRouteImport } from './routes/api/plan-suggest'
import { Route as ApiMentorChatRouteImport } from './routes/api/mentor-chat'
import { Route as ApiKnowledgeReindexRouteImport } from './routes/api/knowledge-reindex'
import { Route as ApiKnowledgeIngestRouteImport } from './routes/api/knowledge-ingest'
import { Route as ApiGoalBreakdownRouteImport } from './routes/api/goal-breakdown'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVisionRouteImport } from './routes/_authenticated/vision'
import { Route as AuthenticatedValuesRouteImport } from './routes/_authenticated/values'
import { Route as AuthenticatedSessionRouteImport } from './routes/_authenticated/session'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrioritiesRouteImport } from './routes/_authenticated/priorities'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as SesijaTokenIndexRouteImport } from './routes/sesija.$token.index'
import { Route as AuthenticatedAskIndexRouteImport } from './routes/_authenticated/ask.index'
import { Route as SesijaTokenPabaigaRouteImport } from './routes/sesija.$token.pabaiga'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAskThreadIdRouteImport } from './routes/_authenticated/ask.$threadId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicClaritySlotsRouteImport } from './routes/api/public/clarity/slots'
import { Route as ApiPublicClarityMessageRouteImport } from './routes/api/public/clarity/message'
import { Route as ApiPublicClarityInterestRouteImport } from './routes/api/public/clarity/interest'
import { Route as ApiPublicClarityHistoryRouteImport } from './routes/api/public/clarity/history'
import { Route as ApiPublicClarityFinishRouteImport } from './routes/api/public/clarity/finish'
import { Route as ApiPublicClarityBookRouteImport } from './routes/api/public/clarity/book'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RezervacijaRoute = RezervacijaRouteImport.update({
  id: '/rezervacija',
  path: '/rezervacija',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SesijaTokenRoute = SesijaTokenRouteImport.update({
  id: '/sesija/$token',
  path: '/sesija/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionAlignmentRoute = ApiVisionAlignmentRouteImport.update({
  id: '/api/vision-alignment',
  path: '/api/vision-alignment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValueSimilaritiesRoute = ApiValueSimilaritiesRouteImport.update({
  id: '/api/value-similarities',
  path: '/api/value-similarities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanSuggestRoute = ApiPlanSuggestRouteImport.update({
  id: '/api/plan-suggest',
  path: '/api/plan-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorChatRoute = ApiMentorChatRouteImport.update({
  id: '/api/mentor-chat',
  path: '/api/mentor-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeReindexRoute = ApiKnowledgeReindexRouteImport.update({
  id: '/api/knowledge-reindex',
  path: '/api/knowledge-reindex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeIngestRoute = ApiKnowledgeIngestRouteImport.update({
  id: '/api/knowledge-ingest',
  path: '/api/knowledge-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoalBreakdownRoute = ApiGoalBreakdownRouteImport.update({
  id: '/api/goal-breakdown',
  path: '/api/goal-breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisionRoute = AuthenticatedVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedValuesRoute = AuthenticatedValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionRoute = AuthenticatedSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrioritiesRoute = AuthenticatedPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const SesijaTokenIndexRoute = SesijaTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SesijaTokenRoute,
} as any)
const AuthenticatedAskIndexRoute = AuthenticatedAskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAskRoute,
} as any)
const SesijaTokenPabaigaRoute = SesijaTokenPabaigaRouteImport.update({
  id: '/pabaiga',
  path: '/pabaiga',
  getParentRoute: () => SesijaTokenRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAskThreadIdRoute =
  AuthenticatedAskThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAskRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClaritySlotsRoute = ApiPublicClaritySlotsRouteImport.update({
  id: '/api/public/clarity/slots',
  path: '/api/public/clarity/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClarityMessageRoute = ApiPublicClarityMessageRouteImport.update({
  id: '/api/public/clarity/message',
  path: '/api/public/clarity/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClarityInterestRoute =
  ApiPublicClarityInterestRouteImport.update({
    id: '/api/public/clarity/interest',
    path: '/api/public/clarity/interest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClarityHistoryRoute = ApiPublicClarityHistoryRouteImport.update({
  id: '/api/public/clarity/history',
  path: '/api/public/clarity/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClarityFinishRoute = ApiPublicClarityFinishRouteImport.update({
  id: '/api/public/clarity/finish',
  path: '/api/public/clarity/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClarityBookRoute = ApiPublicClarityBookRouteImport.update({
  id: '/api/public/clarity/book',
  path: '/api/public/clarity/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/rezervacija': typeof RezervacijaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ask': typeof AuthenticatedAskRouteWithChildren
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/session': typeof AuthenticatedSessionRoute
  '/values': typeof AuthenticatedValuesRoute
  '/vision': typeof AuthenticatedVisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/goal-breakdown': typeof ApiGoalBreakdownRoute
  '/api/knowledge-ingest': typeof ApiKnowledgeIngestRoute
  '/api/knowledge-reindex': typeof ApiKnowledgeReindexRoute
  '/api/mentor-chat': typeof ApiMentorChatRoute
  '/api/plan-suggest': typeof ApiPlanSuggestRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/value-similarities': typeof ApiValueSimilaritiesRoute
  '/api/vision-alignment': typeof ApiVisionAlignmentRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/sesija/$token': typeof SesijaTokenRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/ask/$threadId': typeof AuthenticatedAskThreadIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/sesija/$token/pabaiga': typeof SesijaTokenPabaigaRoute
  '/ask/': typeof AuthenticatedAskIndexRoute
  '/sesija/$token/': typeof SesijaTokenIndexRoute
  '/api/public/clarity/book': typeof ApiPublicClarityBookRoute
  '/api/public/clarity/finish': typeof ApiPublicClarityFinishRoute
  '/api/public/clarity/history': typeof ApiPublicClarityHistoryRoute
  '/api/public/clarity/interest': typeof ApiPublicClarityInterestRoute
  '/api/public/clarity/message': typeof ApiPublicClarityMessageRoute
  '/api/public/clarity/slots': typeof ApiPublicClaritySlotsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/rezervacija': typeof RezervacijaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/priorities': typeof AuthenticatedPrioritiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/session': typeof AuthenticatedSessionRoute
  '/values': typeof AuthenticatedValuesRoute
  '/vision': typeof AuthenticatedVisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/goal-breakdown': typeof ApiGoalBreakdownRoute
  '/api/knowledge-ingest': typeof ApiKnowledgeIngestRoute
  '/api/knowledge-reindex': typeof ApiKnowledgeReindexRoute
  '/api/mentor-chat': typeof ApiMentorChatRoute
  '/api/plan-suggest': typeof ApiPlanSuggestRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/value-similarities': typeof ApiValueSimilaritiesRoute
  '/api/vision-alignment': typeof ApiVisionAlignmentRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/ask/$threadId': typeof AuthenticatedAskThreadIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/sesija/$token/pabaiga': typeof SesijaTokenPabaigaRoute
  '/ask': typeof AuthenticatedAskIndexRoute
  '/sesija/$token': typeof SesijaTokenIndexRoute
  '/api/public/clarity/book': typeof ApiPublicClarityBookRoute
  '/api/public/clarity/finish': typeof ApiPublicClarityFinishRoute
  '/api/public/clarity/history': typeof ApiPublicClarityHistoryRoute
  '/api/public/clarity/interest': typeof ApiPublicClarityInterestRoute
  '/api/public/clarity/message': typeof ApiPublicClarityMessageRoute
  '/api/public/clarity/slots': typeof ApiPublicClaritySlotsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/rezervacija': typeof RezervacijaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ask': typeof AuthenticatedAskRouteWithChildren
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/priorities': typeof AuthenticatedPrioritiesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/session': typeof AuthenticatedSessionRoute
  '/_authenticated/values': typeof AuthenticatedValuesRoute
  '/_authenticated/vision': typeof AuthenticatedVisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/goal-breakdown': typeof ApiGoalBreakdownRoute
  '/api/knowledge-ingest': typeof ApiKnowledgeIngestRoute
  '/api/knowledge-reindex': typeof ApiKnowledgeReindexRoute
  '/api/mentor-chat': typeof ApiMentorChatRoute
  '/api/plan-suggest': typeof ApiPlanSuggestRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/value-similarities': typeof ApiValueSimilaritiesRoute
  '/api/vision-alignment': typeof ApiVisionAlignmentRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/sesija/$token': typeof SesijaTokenRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/ask/$threadId': typeof AuthenticatedAskThreadIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/sesija/$token/pabaiga': typeof SesijaTokenPabaigaRoute
  '/_authenticated/ask/': typeof AuthenticatedAskIndexRoute
  '/sesija/$token/': typeof SesijaTokenIndexRoute
  '/api/public/clarity/book': typeof ApiPublicClarityBookRoute
  '/api/public/clarity/finish': typeof ApiPublicClarityFinishRoute
  '/api/public/clarity/history': typeof ApiPublicClarityHistoryRoute
  '/api/public/clarity/interest': typeof ApiPublicClarityInterestRoute
  '/api/public/clarity/message': typeof ApiPublicClarityMessageRoute
  '/api/public/clarity/slots': typeof ApiPublicClaritySlotsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/rezervacija'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/ask'
    | '/goals'
    | '/insights'
    | '/journal'
    | '/knowledge'
    | '/priorities'
    | '/profile'
    | '/progress'
    | '/resources'
    | '/session'
    | '/values'
    | '/vision'
    | '/api/chat'
    | '/api/goal-breakdown'
    | '/api/knowledge-ingest'
    | '/api/knowledge-reindex'
    | '/api/mentor-chat'
    | '/api/plan-suggest'
    | '/api/transcribe'
    | '/api/value-similarities'
    | '/api/vision-alignment'
    | '/email/unsubscribe'
    | '/sesija/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/ask/$threadId'
    | '/lovable/email/suppression'
    | '/sesija/$token/pabaiga'
    | '/ask/'
    | '/sesija/$token/'
    | '/api/public/clarity/book'
    | '/api/public/clarity/finish'
    | '/api/public/clarity/history'
    | '/api/public/clarity/interest'
    | '/api/public/clarity/message'
    | '/api/public/clarity/slots'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/rezervacija'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/goals'
    | '/insights'
    | '/journal'
    | '/knowledge'
    | '/priorities'
    | '/profile'
    | '/progress'
    | '/resources'
    | '/session'
    | '/values'
    | '/vision'
    | '/api/chat'
    | '/api/goal-breakdown'
    | '/api/knowledge-ingest'
    | '/api/knowledge-reindex'
    | '/api/mentor-chat'
    | '/api/plan-suggest'
    | '/api/transcribe'
    | '/api/value-similarities'
    | '/api/vision-alignment'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/ask/$threadId'
    | '/lovable/email/suppression'
    | '/sesija/$token/pabaiga'
    | '/ask'
    | '/sesija/$token'
    | '/api/public/clarity/book'
    | '/api/public/clarity/finish'
    | '/api/public/clarity/history'
    | '/api/public/clarity/interest'
    | '/api/public/clarity/message'
    | '/api/public/clarity/slots'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/rezervacija'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/ask'
    | '/_authenticated/goals'
    | '/_authenticated/insights'
    | '/_authenticated/journal'
    | '/_authenticated/knowledge'
    | '/_authenticated/priorities'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/resources'
    | '/_authenticated/session'
    | '/_authenticated/values'
    | '/_authenticated/vision'
    | '/api/chat'
    | '/api/goal-breakdown'
    | '/api/knowledge-ingest'
    | '/api/knowledge-reindex'
    | '/api/mentor-chat'
    | '/api/plan-suggest'
    | '/api/transcribe'
    | '/api/value-similarities'
    | '/api/vision-alignment'
    | '/email/unsubscribe'
    | '/sesija/$token'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/ask/$threadId'
    | '/lovable/email/suppression'
    | '/sesija/$token/pabaiga'
    | '/_authenticated/ask/'
    | '/sesija/$token/'
    | '/api/public/clarity/book'
    | '/api/public/clarity/finish'
    | '/api/public/clarity/history'
    | '/api/public/clarity/interest'
    | '/api/public/clarity/message'
    | '/api/public/clarity/slots'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  RezervacijaRoute: typeof RezervacijaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGoalBreakdownRoute: typeof ApiGoalBreakdownRoute
  ApiKnowledgeIngestRoute: typeof ApiKnowledgeIngestRoute
  ApiKnowledgeReindexRoute: typeof ApiKnowledgeReindexRoute
  ApiMentorChatRoute: typeof ApiMentorChatRoute
  ApiPlanSuggestRoute: typeof ApiPlanSuggestRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiValueSimilaritiesRoute: typeof ApiValueSimilaritiesRoute
  ApiVisionAlignmentRoute: typeof ApiVisionAlignmentRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  SesijaTokenRoute: typeof SesijaTokenRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicClarityBookRoute: typeof ApiPublicClarityBookRoute
  ApiPublicClarityFinishRoute: typeof ApiPublicClarityFinishRoute
  ApiPublicClarityHistoryRoute: typeof ApiPublicClarityHistoryRoute
  ApiPublicClarityInterestRoute: typeof ApiPublicClarityInterestRoute
  ApiPublicClarityMessageRoute: typeof ApiPublicClarityMessageRoute
  ApiPublicClaritySlotsRoute: typeof ApiPublicClaritySlotsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezervacija': {
      id: '/rezervacija'
      path: '/rezervacija'
      fullPath: '/rezervacija'
      preLoaderRoute: typeof RezervacijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesija/$token': {
      id: '/sesija/$token'
      path: '/sesija/$token'
      fullPath: '/sesija/$token'
      preLoaderRoute: typeof SesijaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision-alignment': {
      id: '/api/vision-alignment'
      path: '/api/vision-alignment'
      fullPath: '/api/vision-alignment'
      preLoaderRoute: typeof ApiVisionAlignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/value-similarities': {
      id: '/api/value-similarities'
      path: '/api/value-similarities'
      fullPath: '/api/value-similarities'
      preLoaderRoute: typeof ApiValueSimilaritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan-suggest': {
      id: '/api/plan-suggest'
      path: '/api/plan-suggest'
      fullPath: '/api/plan-suggest'
      preLoaderRoute: typeof ApiPlanSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor-chat': {
      id: '/api/mentor-chat'
      path: '/api/mentor-chat'
      fullPath: '/api/mentor-chat'
      preLoaderRoute: typeof ApiMentorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge-reindex': {
      id: '/api/knowledge-reindex'
      path: '/api/knowledge-reindex'
      fullPath: '/api/knowledge-reindex'
      preLoaderRoute: typeof ApiKnowledgeReindexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge-ingest': {
      id: '/api/knowledge-ingest'
      path: '/api/knowledge-ingest'
      fullPath: '/api/knowledge-ingest'
      preLoaderRoute: typeof ApiKnowledgeIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/goal-breakdown': {
      id: '/api/goal-breakdown'
      path: '/api/goal-breakdown'
      fullPath: '/api/goal-breakdown'
      preLoaderRoute: typeof ApiGoalBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vision': {
      id: '/_authenticated/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof AuthenticatedVisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/values': {
      id: '/_authenticated/values'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof AuthenticatedValuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session': {
      id: '/_authenticated/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AuthenticatedSessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/priorities': {
      id: '/_authenticated/priorities'
      path: '/priorities'
      fullPath: '/priorities'
      preLoaderRoute: typeof AuthenticatedPrioritiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sesija/$token/': {
      id: '/sesija/$token/'
      path: '/'
      fullPath: '/sesija/$token/'
      preLoaderRoute: typeof SesijaTokenIndexRouteImport
      parentRoute: typeof SesijaTokenRoute
    }
    '/_authenticated/ask/': {
      id: '/_authenticated/ask/'
      path: '/'
      fullPath: '/ask/'
      preLoaderRoute: typeof AuthenticatedAskIndexRouteImport
      parentRoute: typeof AuthenticatedAskRoute
    }
    '/sesija/$token/pabaiga': {
      id: '/sesija/$token/pabaiga'
      path: '/pabaiga'
      fullPath: '/sesija/$token/pabaiga'
      preLoaderRoute: typeof SesijaTokenPabaigaRouteImport
      parentRoute: typeof SesijaTokenRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ask/$threadId': {
      id: '/_authenticated/ask/$threadId'
      path: '/$threadId'
      fullPath: '/ask/$threadId'
      preLoaderRoute: typeof AuthenticatedAskThreadIdRouteImport
      parentRoute: typeof AuthenticatedAskRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/slots': {
      id: '/api/public/clarity/slots'
      path: '/api/public/clarity/slots'
      fullPath: '/api/public/clarity/slots'
      preLoaderRoute: typeof ApiPublicClaritySlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/message': {
      id: '/api/public/clarity/message'
      path: '/api/public/clarity/message'
      fullPath: '/api/public/clarity/message'
      preLoaderRoute: typeof ApiPublicClarityMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/interest': {
      id: '/api/public/clarity/interest'
      path: '/api/public/clarity/interest'
      fullPath: '/api/public/clarity/interest'
      preLoaderRoute: typeof ApiPublicClarityInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/history': {
      id: '/api/public/clarity/history'
      path: '/api/public/clarity/history'
      fullPath: '/api/public/clarity/history'
      preLoaderRoute: typeof ApiPublicClarityHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/finish': {
      id: '/api/public/clarity/finish'
      path: '/api/public/clarity/finish'
      fullPath: '/api/public/clarity/finish'
      preLoaderRoute: typeof ApiPublicClarityFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clarity/book': {
      id: '/api/public/clarity/book'
      path: '/api/public/clarity/book'
      fullPath: '/api/public/clarity/book'
      preLoaderRoute: typeof ApiPublicClarityBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAskRouteChildren {
  AuthenticatedAskThreadIdRoute: typeof AuthenticatedAskThreadIdRoute
  AuthenticatedAskIndexRoute: typeof AuthenticatedAskIndexRoute
}

const AuthenticatedAskRouteChildren: AuthenticatedAskRouteChildren = {
  AuthenticatedAskThreadIdRoute: AuthenticatedAskThreadIdRoute,
  AuthenticatedAskIndexRoute: AuthenticatedAskIndexRoute,
}

const AuthenticatedAskRouteWithChildren =
  AuthenticatedAskRoute._addFileChildren(AuthenticatedAskRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAskRoute: typeof AuthenticatedAskRouteWithChildren
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedPrioritiesRoute: typeof AuthenticatedPrioritiesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSessionRoute: typeof AuthenticatedSessionRoute
  AuthenticatedValuesRoute: typeof AuthenticatedValuesRoute
  AuthenticatedVisionRoute: typeof AuthenticatedVisionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAskRoute: AuthenticatedAskRouteWithChildren,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedPrioritiesRoute: AuthenticatedPrioritiesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSessionRoute: AuthenticatedSessionRoute,
  AuthenticatedValuesRoute: AuthenticatedValuesRoute,
  AuthenticatedVisionRoute: AuthenticatedVisionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SesijaTokenRouteChildren {
  SesijaTokenPabaigaRoute: typeof SesijaTokenPabaigaRoute
  SesijaTokenIndexRoute: typeof SesijaTokenIndexRoute
}

const SesijaTokenRouteChildren: SesijaTokenRouteChildren = {
  SesijaTokenPabaigaRoute: SesijaTokenPabaigaRoute,
  SesijaTokenIndexRoute: SesijaTokenIndexRoute,
}

const SesijaTokenRouteWithChildren = SesijaTokenRoute._addFileChildren(
  SesijaTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  RezervacijaRoute: RezervacijaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGoalBreakdownRoute: ApiGoalBreakdownRoute,
  ApiKnowledgeIngestRoute: ApiKnowledgeIngestRoute,
  ApiKnowledgeReindexRoute: ApiKnowledgeReindexRoute,
  ApiMentorChatRoute: ApiMentorChatRoute,
  ApiPlanSuggestRoute: ApiPlanSuggestRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiValueSimilaritiesRoute: ApiValueSimilaritiesRoute,
  ApiVisionAlignmentRoute: ApiVisionAlignmentRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  SesijaTokenRoute: SesijaTokenRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicClarityBookRoute: ApiPublicClarityBookRoute,
  ApiPublicClarityFinishRoute: ApiPublicClarityFinishRoute,
  ApiPublicClarityHistoryRoute: ApiPublicClarityHistoryRoute,
  ApiPublicClarityInterestRoute: ApiPublicClarityInterestRoute,
  ApiPublicClarityMessageRoute: ApiPublicClarityMessageRoute,
  ApiPublicClaritySlotsRoute: ApiPublicClaritySlotsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
